# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - RETICULATE_TEST_ENVIRONMENTS=1

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - rm miniconda.sh
  - source $HOME/miniconda/bin/activate base
  - conda install numpy pandas scipy docutils

addons:
  apt:
    packages:
      - python2.7
      - python-numpy
      - python-scipy
      - python-virtualenv
      - python3-venv
