# DO NOT CHANGE the "init" and "install" sections below

image: Visual Studio 2015

environment:
  NOT_CRAN: true
  USE_RTOOLS: true
  RETICULATE_TEST_ENVIRONMENTS: 1  
  matrix:
   #- PYTHON: "C:\\Python27"
     #RETICULATE_PYTHON: "C:\\Python27"
     #PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin;C:\\Miniconda-x64\\Scripts"
    - PYTHON: "C:\\Python34"
      RETICULATE_PYTHON: "C:\\Python34"
      PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin;C:\\Miniconda34-x64\\Scripts"
    - PYTHON: "C:\\Python35"
      RETICULATE_PYTHON: "C:\\Python35"
      PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin;C:\\Miniconda35-x64\\Scripts"
    - PYTHON: "C:\\Python36"
      RETICULATE_PYTHON: "C:\\Python36"
      PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin;C:\\Miniconda36-x64\\Scripts"

matrix:
  fast_finish: true

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - "%PYTHON%\\python.exe -m pip install setuptools numpy"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
